let targyakAdata = [
  {
    id: "bukk_fa",
    name: "Bükkfa",
    price: "20000",
    img: "/csapatos_munka/!LOCAL/Pictures/faanyagok/Fadeszka_Bükkfa.png",
    img_siker: "/csapatos_munka/!LOCAL/Pictures/succes_hibatlan.gif",
    leiras:
      "A bükkfa azon keményfa fajták közé tartozik, amely nagyon jól megmunkálható, esztergályozható, szép és egységes erezetű, és nem szálkásodik.",
  },

  {
    id: "",
    name: "",
    price: "20000",
    img: "/csapatos_munka/!LOCAL/Pictures/faanyagok/",
    img_siker: "/csapatos_munka/!LOCAL/Pictures/succes_hibatlan.gif",
    leiras: "",
  },
  {
    id: "",
    name: "",
    price: "20000",
    img: "/csapatos_munka/!LOCAL/Pictures/faanyagok/",
    img_siker: "/csapatos_munka/!LOCAL/Pictures/succes_hibatlan.gif",
    leiras: "",
  },
  {
    id: "",
    name: "",
    price: "20000",
    img: "/csapatos_munka/!LOCAL/Pictures/faanyagok/",
    img_siker: "/csapatos_munka/!LOCAL/Pictures/succes_hibatlan.gif",
    leiras: "",
  },
  {
    id: "",
    name: "",
    price: "20000",
    img: "/csapatos_munka/!LOCAL/Pictures/faanyagok/",
    img_siker: "/csapatos_munka/!LOCAL/Pictures/succes_hibatlan.gif",
    leiras: "",
  },
  {
    id: "",
    name: "",
    price: "20000",
    img: "/csapatos_munka/!LOCAL/Pictures/faanyagok/",
    img_siker: "/csapatos_munka/!LOCAL/Pictures/succes_hibatlan.gif",
    leiras: "",
  },
  {
    id: "",
    name: "",
    price: "20000",
    img: "/csapatos_munka/!LOCAL/Pictures/faanyagok/",
    img_siker: "/csapatos_munka/!LOCAL/Pictures/succes_hibatlan.gif",
    leiras: "",
  },
  {
    id: "",
    name: "",
    price: "20000",
    img: "/csapatos_munka/!LOCAL/Pictures/faanyagok/",
    img_siker: "/csapatos_munka/!LOCAL/Pictures/succes_hibatlan.gif",
    leiras: "",
  },
];
